import { makeStyles } from 'tss-react/mui'

const useStyles = makeStyles()((theme) => ({
  DrawerContainer: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: '100vw',
    height: '100vh',
    padding: `0 ${theme.spacing(4)}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexWrap: 'nowrap',
    color: theme.custom.lightFont,
    backgroundColor: theme.custom.blackColor,
    zIndex: 1,
  },
  DrawerTopBar: {
    width: '100%',
    height: '100px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing(8),
    paddingBottom: theme.spacing(0),
    borderBottom: `1px solid ${theme.custom.whiteColor}`,
  },
  LinksContainer: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    paddingTop: theme.spacing(15),
  },
  pageLink: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    color: theme.custom.lightFont,
    paddingBottom: theme.spacing(8),
    margin: `0 ${theme.spacing(8)}`,
    fontFamily: 'Nunito Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: 36,
    textAlign: 'center',
    textTransform: 'uppercase',
    cursor: 'pointer',
    [theme.breakpoints.down('md')]: {
      textAlign: 'start',
      alignItems: 'center',
      justifyContent: 'flex-start',
      fontSize: 24,
      paddingBottom: theme.spacing(4),
    },
  },
  subMenuLink: {
    width: '100%',
    textDecoration: 'none',
    color: theme.custom.lightFont,
    fontFamily: 'Nunito Sans',
    fontStyle: 'normal',
    Weight: 800,
    Size: 18,
    LineHeight: 24.55,
    textTransform: 'uppercase',
    textAlign: 'start',
    cursor: 'pointer',
    Link: {
      textDecoration: 'none',
    },
  },
  mobileViewLinks: {
    [theme.breakpoints.up('md')]: {
      display: 'none',
    },
  },
}))

export default useStyles
